owner                     = "owner@gmail.com"
project_current_name      = "XXXXXX"
default_region            = "us-gov-west-1"
aws_env                   = "dev"
shortEnv                  = "d"
logs_s3_retention_region  = 2
logs_s3_retention_central = 7
ou_id                     = "o-1234567890"      # NOTE: Replaced real one for security reasons
is_gov = true
account_id                = "123456789012"  # NOTE: Replaced real one for security reasons